### ISSUE TITLE
Issue about the results of function vis()

### ISSUE THREAD

**Issue by gaosh** [elbamos/largeVis#14] opened 2016-08-02 19:39 UTC
Firstly, thanks for the nice implementation. 
I tried this algorithm on the cifar 10 dataset. The problem is that I got different results from the same input. Is there any method to deal with it, and make the results more stable?

**Comment by elbamos** [comment] 2016-08-03 02:47
In the first place, I'd strongly encourage you to use the version in branch `reference` (which hopefully will be merged into and become branch 0.1.6 tonight...)  A lot of bugs have been fixed.  

The new branch uses a difference random number generator where its possible to set the random seed properly, but I haven't written code to do that yet.  I may try to get to it this week, although if you wanted to make a PR, what needs to be changed is pretty straightforward and it wouldn't take you very long.

**Comment by elbamos** [comment] 2016-08-03 04:41
I'm really eager to see what the results are of running this on cifar!

**Comment by gaosh** [comment] 2016-08-03 18:24
Thanks for the reply. There are the results comes from 256 dimension
features of cifar10 test set.

**Comment by elbamos** [comment] 2016-08-07 20:49
@gaosh Branch 0.1.7, which I've just pushed, lets you set a random seed for reproducibility.

Note that setting the seed will impact performance, because it is also necessary to turn off multithreading or the results would be non-deterministic.

**Comment by gaosh** [comment] 2016-08-08 18:25
Ok, I will try this new version. Thanks a lot.

2016年8月7日星期日，elbamos notifications@github.com 写道：

**Comment by elbamos** [comment] 2016-08-18 04:47
@gaosh If 0.1.7 worked, do you want to close this issue?

**Comment by gaosh** [comment] 2016-08-18 17:11
Yes, I want to close the issue.

2016年8月18日星期四，elbamos notifications@github.com 写道：

**Closed as completed** 2016-08-20 20:08 UTC
